//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAutoServicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.Costumers = new HashSet<Costumer>();
            this.Costumers1 = new HashSet<Costumer>();
            this.ServiceBookings = new HashSet<ServiceBooking>();
            this.ServiceBookings1 = new HashSet<ServiceBooking>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<Costumer> Costumers { get; set; }
        public virtual ICollection<Costumer> Costumers1 { get; set; }
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
        public virtual ICollection<ServiceBooking> ServiceBookings1 { get; set; }
    }
}
