//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAutoServicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string BillN0 { get; set; }
        public string ServiceNo { get; set; }
        public string SolutionNo { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Solution Solution { get; set; }
    }
}
