//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAutoServicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanic
    {
        public Mechanic()
        {
            this.ServiceBookings = new HashSet<ServiceBooking>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Specilization { get; set; }
        public int Status { get; set; }
        public int EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
    }
}
