//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAutoServicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBooking
    {
        public int Id { get; set; }
        public string ServiceNo { get; set; }
        public int CostumerId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<System.DateTime> ServicedDate { get; set; }
        public int ServicedBy { get; set; }
        public string ServiceType { get; set; }
        public string ServiceStatus { get; set; }
        public string Problem { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public int Status { get; set; }
        public int EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Costumer Costumer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
