//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAutoServicing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Costumers = new HashSet<Costumer>();
            this.ServiceBookings = new HashSet<ServiceBooking>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
        public Nullable<double> EnginePower { get; set; }
        public Nullable<int> FuelCapacity { get; set; }
        public Nullable<int> OilCapacity { get; set; }
        public string Photo { get; set; }
        public int Status { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual ICollection<Costumer> Costumers { get; set; }
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
    }
}
